# Generated by Django 4.2.6 on 2024-03-31 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Details',
            fields=[
                ('user_id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=255, unique=True)),
                ('f_name', models.CharField(db_index=True, max_length=120)),
                ('l_name', models.CharField(db_index=True, max_length=120, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, null=True)),
                ('password', models.CharField(db_index=True, max_length=120)),
                ('mobile_no', models.IntegerField(db_index=True, max_length=15)),
                ('dob', models.DateField(db_index=True)),
                ('location', models.CharField(db_index=True, max_length=200)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User_Details',
            },
        ),
        migrations.CreateModel(
            name='Transaction_history',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_account', models.CharField(db_index=True, max_length=120)),
                ('to_account', models.CharField(db_index=True, max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_details')),
            ],
            options={
                'db_table': 'Transaction_history',
            },
        ),
        migrations.CreateModel(
            name='Account_Details',
            fields=[
                ('user_name', models.CharField(db_index=True, max_length=120)),
                ('acc_no', models.IntegerField(db_index=True, max_length=15, primary_key=True, serialize=False)),
                ('account_type', models.CharField(db_index=True, max_length=120)),
                ('acc_balance', models.FloatField(db_index=True)),
                ('created_date', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('acc_status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user_details')),
            ],
            options={
                'db_table': 'Account_Details',
            },
        ),
    ]
