# Generated by Django 4.2.6 on 2024-04-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='acc_no',
            field=models.IntegerField(db_index=True, max_length=25, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile_no',
            field=models.IntegerField(db_index=True, max_length=50),
        ),
    ]
