# Generated by Django 4.2.6 on 2024-05-02 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='acc_balance',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999999999999999)]),
        ),
        migrations.AlterField(
            model_name='account_details',
            name='acc_no',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999999)]),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='amount',
            field=models.FloatField(db_index=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile_no',
            field=models.BigIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(999999999999999)]),
        ),
    ]
