# Generated by Django 4.2.6 on 2024-04-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_details_acc_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_details',
            name='acc_no',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='mobile_no',
            field=models.IntegerField(db_index=True),
        ),
    ]
