# Generated by Django 4.2.6 on 2024-05-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_rename_from_account_transaction_history_from_account_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_history',
            name='remarks',
            field=models.CharField(db_index=True, default='others', max_length=120),
        ),
        migrations.AlterField(
            model_name='transaction_history',
            name='transaction_type',
            field=models.CharField(max_length=50),
        ),
    ]
